# Generated by Django 2.1.15 on 2022-08-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fomula', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Объект 3',
                'verbose_name_plural': 'Объект 3',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Ссылка')),
                ('ancestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move_journal.Quide', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Объект 1',
                'verbose_name_plural': 'Объект 1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.DateField(blank=True, null=True, verbose_name='Учетный период')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move_journal.Formula', verbose_name='Формула')),
                ('quide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move_journal.Quide', verbose_name='Справочное наименование')),
            ],
            options={
                'verbose_name': 'Объект 2',
                'verbose_name_plural': 'Объект 2',
                'managed': True,
            },
        ),
    ]
