# Generated by Django 2.1.15 on 2022-08-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('move_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move_journal.Formula', verbose_name='Формула'),
        ),
    ]
