# Generated by Django 2.1.15 on 2022-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_journal', '0003_auto_20220816_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='formula',
        ),
        migrations.AddField(
            model_name='quide',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
    ]
