# Generated by Django 2.1.15 on 2022-09-01 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('move_journal', '0005_remove_quide_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quide',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='move_journal.Quide', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='quide',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='value',
            name='up',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 1), null=True, verbose_name='Учетный период'),
        ),
    ]
