# Generated by Django 2.1.15 on 2022-09-01 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_journal', '0006_auto_20220901_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='up',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Учетный период'),
        ),
    ]
